name: Django CI Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SECRET_KEY: "django-insecure-7l3po6b6ss%5ng+fnevd@g!7a3(9%l1lda@@)2frv+3%)t3#d9"
      DATABASE_URL: "sqlite:///db.sqlite3"  # Using SQLite for testing simplicity

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        python manage.py migrate

    - name: Run tests
      run: |
        python manage.py test

    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 . --exclude=migrations,__pycache__
